dist: xenial
language: python
python:
    - "3.7"

install:
    - pip install https://download.pytorch.org/whl/cpu/torch-1.1.0-cp37-cp37m-linux_x86_64.whl
    - pip install -r requirements.txt

script:
    - pytest
